eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

grpc:
  client:
    user:
      address: 'static://127.0.0.1:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    product:
      address: 'static://127.0.0.1:50052'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    order:
      address: 'static://127.0.0.1:50053'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  port: 8084

spring:
  application:
    name: aggregator-service

springdoc:
  packages-to-scan: org.atlas.framework.rest.server.aggregator.controller

app:
  internal:
    user:
      base-url: http://localhost:8081
    product:
      base-url: http://localhost:8082
    order:
      base-url: http://localhost:8083
