// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.user;

public interface ListCustomerRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.ListCustomerRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 id = 1;</code>
   * @return A list containing the id.
   */
  java.util.List<java.lang.Integer> getIdList();
  /**
   * <code>repeated int32 id = 1;</code>
   * @return The count of id.
   */
  int getIdCount();
  /**
   * <code>repeated int32 id = 1;</code>
   * @param index The index of the element to return.
   * @return The id at the given index.
   */
  int getId(int index);
}
