// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.order;

public interface ExportOrderRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.ExportOrderRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 user_id = 2;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>double min_amount = 3;</code>
   * @return The minAmount.
   */
  double getMinAmount();

  /**
   * <code>double max_amount = 4;</code>
   * @return The maxAmount.
   */
  double getMaxAmount();

  /**
   * <code>string address = 5;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string start_created_at = 7;</code>
   * @return The startCreatedAt.
   */
  java.lang.String getStartCreatedAt();
  /**
   * <code>string start_created_at = 7;</code>
   * @return The bytes for startCreatedAt.
   */
  com.google.protobuf.ByteString
      getStartCreatedAtBytes();

  /**
   * <code>string end_created_at = 8;</code>
   * @return The endCreatedAt.
   */
  java.lang.String getEndCreatedAt();
  /**
   * <code>string end_created_at = 8;</code>
   * @return The bytes for endCreatedAt.
   */
  com.google.protobuf.ByteString
      getEndCreatedAtBytes();

  /**
   * <code>string sort = 9;</code>
   * @return The sort.
   */
  java.lang.String getSort();
  /**
   * <code>string sort = 9;</code>
   * @return The bytes for sort.
   */
  com.google.protobuf.ByteString
      getSortBytes();

  /**
   * <code>string file_type = 10;</code>
   * @return The fileType.
   */
  java.lang.String getFileType();
  /**
   * <code>string file_type = 10;</code>
   * @return The bytes for fileType.
   */
  com.google.protobuf.ByteString
      getFileTypeBytes();
}
