// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.order;

public interface ExportOrderResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.ExportOrderResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file_content = 1;</code>
   * @return The fileContent.
   */
  com.google.protobuf.ByteString getFileContent();
}
