// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.order;

public interface OrderStatusProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.OrderStatusProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
