// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.order;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderItemProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderItemProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderPageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderPageProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_ListOrderRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_ListOrderRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_GetOrderRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_GetOrderRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_PlaceOrderRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_PlaceOrderRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_PlaceOrderResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_PlaceOrderResponseProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_ImportOrderRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_ImportOrderRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_ExportOrderRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_ExportOrderRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_ExportOrderResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_ExportOrderResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\005order\032\033google/protobuf/em" +
      "pty.proto\032\014common.proto\"\261\001\n\nOrderProto\022\n" +
      "\n\002id\030\001 \001(\005\022\'\n\010customer\030\002 \001(\0132\025.common.Cu" +
      "stomerProto\022)\n\norder_item\030\003 \003(\0132\025.order." +
      "OrderItemProto\022\016\n\006amount\030\004 \001(\001\022\017\n\007addres" +
      "s\030\005 \001(\t\022\016\n\006status\030\006 \001(\t\022\022\n\ncreated_at\030\007 " +
      "\001(\t\"c\n\016OrderItemProto\022\022\n\nproduct_id\030\001 \001(" +
      "\005\022\024\n\014product_name\030\002 \001(\t\022\025\n\rproduct_price" +
      "\030\003 \001(\001\022\020\n\010quantity\030\004 \001(\005\"G\n\016OrderPagePro" +
      "to\022 \n\005order\030\001 \003(\0132\021.order.OrderProto\022\023\n\013" +
      "total_count\030\002 \001(\003\"\331\001\n\025ListOrderRequestPr" +
      "oto\022\n\n\002id\030\001 \001(\005\022\017\n\007user_id\030\002 \001(\005\022\022\n\nmin_" +
      "amount\030\003 \001(\001\022\022\n\nmax_amount\030\004 \001(\001\022\017\n\007addr" +
      "ess\030\005 \001(\t\022\016\n\006status\030\006 \001(\t\022\030\n\020start_creat" +
      "ed_at\030\007 \001(\t\022\026\n\016end_created_at\030\010 \001(\t\022\014\n\004p" +
      "age\030\t \001(\005\022\014\n\004size\030\n \001(\005\022\014\n\004sort\030\013 \001(\t\"\"\n" +
      "\024GetOrderRequestProto\022\n\n\002id\030\001 \001(\005\"C\n\026Pla" +
      "ceOrderRequestProto\022)\n\norder_item\030\001 \003(\0132" +
      "\025.order.OrderItemProto\"%\n\027PlaceOrderResp" +
      "onseProto\022\n\n\002id\030\001 \001(\005\"B\n\027ImportOrderRequ" +
      "estProto\022\021\n\tfile_type\030\001 \001(\t\022\024\n\014file_cont" +
      "ent\030\002 \001(\014\"\322\001\n\027ExportOrderRequestProto\022\n\n" +
      "\002id\030\001 \001(\005\022\017\n\007user_id\030\002 \001(\005\022\022\n\nmin_amount" +
      "\030\003 \001(\001\022\022\n\nmax_amount\030\004 \001(\001\022\017\n\007address\030\005 " +
      "\001(\t\022\016\n\006status\030\006 \001(\t\022\030\n\020start_created_at\030" +
      "\007 \001(\t\022\026\n\016end_created_at\030\010 \001(\t\022\014\n\004sort\030\t " +
      "\001(\t\022\021\n\tfile_type\030\n \001(\t\"0\n\030ExportOrderRes" +
      "ponseProto\022\024\n\014file_content\030\001 \001(\0142\372\002\n\014Ord" +
      "erService\022B\n\tListOrder\022\034.order.ListOrder" +
      "RequestProto\032\025.order.OrderPageProto\"\000\022<\n" +
      "\010GetOrder\022\033.order.GetOrderRequestProto\032\021" +
      ".order.OrderProto\"\000\022M\n\nPlaceOrder\022\035.orde" +
      "r.PlaceOrderRequestProto\032\036.order.PlaceOr" +
      "derResponseProto\"\000\022G\n\013ImportOrder\022\036.orde" +
      "r.ImportOrderRequestProto\032\026.google.proto" +
      "buf.Empty\"\000\022P\n\013ExportOrder\022\036.order.Expor" +
      "tOrderRequestProto\032\037.order.ExportOrderRe" +
      "sponseProto\"\000B+\n\'org.atlas.framework.grp" +
      "c.protobuf.orderP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          org.atlas.framework.grpc.protobuf.common.Common.getDescriptor(),
        });
    internal_static_order_OrderProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_OrderProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderProto_descriptor,
        new java.lang.String[] { "Id", "Customer", "OrderItem", "Amount", "Address", "Status", "CreatedAt", });
    internal_static_order_OrderItemProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_OrderItemProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderItemProto_descriptor,
        new java.lang.String[] { "ProductId", "ProductName", "ProductPrice", "Quantity", });
    internal_static_order_OrderPageProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_order_OrderPageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderPageProto_descriptor,
        new java.lang.String[] { "Order", "TotalCount", });
    internal_static_order_ListOrderRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_order_ListOrderRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_ListOrderRequestProto_descriptor,
        new java.lang.String[] { "Id", "UserId", "MinAmount", "MaxAmount", "Address", "Status", "StartCreatedAt", "EndCreatedAt", "Page", "Size", "Sort", });
    internal_static_order_GetOrderRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_order_GetOrderRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_GetOrderRequestProto_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_order_PlaceOrderRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_order_PlaceOrderRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_PlaceOrderRequestProto_descriptor,
        new java.lang.String[] { "OrderItem", });
    internal_static_order_PlaceOrderResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_order_PlaceOrderResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_PlaceOrderResponseProto_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_order_ImportOrderRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_order_ImportOrderRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_ImportOrderRequestProto_descriptor,
        new java.lang.String[] { "FileType", "FileContent", });
    internal_static_order_ExportOrderRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_order_ExportOrderRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_ExportOrderRequestProto_descriptor,
        new java.lang.String[] { "Id", "UserId", "MinAmount", "MaxAmount", "Address", "Status", "StartCreatedAt", "EndCreatedAt", "Sort", "FileType", });
    internal_static_order_ExportOrderResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_order_ExportOrderResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_ExportOrderResponseProto_descriptor,
        new java.lang.String[] { "FileContent", });
    com.google.protobuf.EmptyProto.getDescriptor();
    org.atlas.framework.grpc.protobuf.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
