// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.order;

public interface OrderItemProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.OrderItemProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 product_id = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>double product_price = 2;</code>
   * @return The productPrice.
   */
  double getProductPrice();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();
}
