// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.order;

public interface PlaceOrderRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.PlaceOrderRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .order.OrderItemProto order_item = 1;</code>
   */
  java.util.List<org.atlas.framework.grpc.protobuf.order.OrderItemProto> 
      getOrderItemList();
  /**
   * <code>repeated .order.OrderItemProto order_item = 1;</code>
   */
  org.atlas.framework.grpc.protobuf.order.OrderItemProto getOrderItem(int index);
  /**
   * <code>repeated .order.OrderItemProto order_item = 1;</code>
   */
  int getOrderItemCount();
  /**
   * <code>repeated .order.OrderItemProto order_item = 1;</code>
   */
  java.util.List<? extends org.atlas.framework.grpc.protobuf.order.OrderItemProtoOrBuilder> 
      getOrderItemOrBuilderList();
  /**
   * <code>repeated .order.OrderItemProto order_item = 1;</code>
   */
  org.atlas.framework.grpc.protobuf.order.OrderItemProtoOrBuilder getOrderItemOrBuilder(
      int index);
}
