eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

grpc:
  server:
    port: 50051

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    mail:
      # Turn off health check mail server
      enabled: false
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  packages-to-scan: org.atlas.framework.rest.server.user.controller

app:
  event:
    kafka:
      consumer:
        topics: reserve_credit_request,quantity_reserved
  outbox:
    enabled: true
