management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    mail:
      # Turn off health check mail server
      enabled: false
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411}
      connect-timeout: 30s
      read-timeout: 10s
  tracing:
    sampling:
      # 1.0 represents 100%, meaning all requests will be traced.
      probability: 1.0

server:
  port: 8093

spring:
  application:
    name: job
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/orders?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  quartz:
    # Quartz can store job and scheduling information in a relational database or RAM.
    # With RAM option, any information will be deleted with application restart.
    job-store-type: memory
    properties:
      org.quartz.scheduler:
        instanceName: DefaultScheduler
        instanceId: AUTO
      org.quartz.threadPool:
        threadNamePrefix: quartz
        threadCount: 10
