apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: gateway-server:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
          ports:
            - containerPort: 8080
          # Liveness Probe: Checks if the app is healthy and should restart if not healthy
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          # Readiness Probe: Checks if the app is ready to receive traffic
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          volumeMounts:
            - name: gateway-server-log
              mountPath: /var/log/gateway-server
          resources:
            requests:
              cpu: "0.25"
              memory: "256Mi"
            limits:
              cpu: "0.50"
              memory: "512Mi"
      volumes:
        - name: gateway-server-log
          persistentVolumeClaim:
            claimName: gateway-server-log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-server-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
