apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-service
spec:
  schedule: "0 0 * * *"  # Runs at midnight every day
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: job-service
        spec:
          containers:
            - name: job-service
              image: job-service:latest
              imagePullPolicy: Never
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "prod"
                - name: MYSQL_URL
                  value: "jdbc:mysql://mysql:3306/db_order?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false"
                - name: MYSQL_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: mysql-username
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: mysql-password
                - name: ZIPKIN_ENDPOINT
                  value: "http://zipkin:9411/api/v2/spans"
              ports:
                - containerPort: 8093
              # Liveness Probe: Checks if the app is healthy and should restart if not healthy
              livenessProbe:
                httpGet:
                  path: /actuator/health/liveness
                  port: 8093
                initialDelaySeconds: 120
                periodSeconds: 30
                failureThreshold: 3
              # Readiness Probe: Checks if the app is ready to receive traffic
              readinessProbe:
                httpGet:
                  path: /actuator/health/readiness
                  port: 8093
                initialDelaySeconds: 120
                periodSeconds: 30
                failureThreshold: 3
              volumeMounts:
                - name: job-service-log
                  mountPath: /var/log/job-service
              resources:
                requests:
                  cpu: "0.25"
                  memory: "256Mi"
                limits:
                  cpu: "0.50"
                  memory: "512Mi"
          restartPolicy: Never
          volumes:
            - name: job-service-log
              persistentVolumeClaim:
                claimName: job-service-log
  successfulJobsHistoryLimit: 3  # Retain 3 successful job histories
  failedJobsHistoryLimit: 1      # Retain 1 failed job history
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-service-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
