apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-server
  template:
    metadata:
      labels:
        app: notification-server
    spec:
      containers:
        - name: notification-server
          image: notification-server:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
            - name: MAIL_SERVER_HOST
              value: "smtp4dev"
          ports:
            - containerPort: 8092
          # Liveness Probe: Checks if the app is healthy and should restart if not healthy
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8092
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          # Readiness Probe: Checks if the app is ready to receive traffic
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8092
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          volumeMounts:
            - name: notification-server-log
              mountPath: /var/log/notification-server
          resources:
            requests:
              cpu: "0.25"
              memory: "256Mi"
            limits:
              cpu: "0.50"
              memory: "512Mi"
      volumes:
        - name: notification-server-log
          persistentVolumeClaim:
            claimName: notification-server-log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-server-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-server
spec:
  selector:
    app: notification-server
  ports:
    - port: 8092
      targetPort: 8092
  type: ClusterIP
