apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtp4dev-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp4dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp4dev
  template:
    metadata:
      labels:
        app: smtp4dev
    spec:
      containers:
        - name: smtp4dev
          image: rnwood/smtp4dev
          ports:
            - containerPort: 80   # Web interface
            - containerPort: 25   # SMTP server
            - containerPort: 143  # IMAP server
          volumeMounts:
            - name: smtp4dev-data
              mountPath: /smtp4dev
      volumes:
        - name: smtp4dev-data
          persistentVolumeClaim:
            claimName: smtp4dev-data
---
apiVersion: v1
kind: Service
metadata:
  name: smtp4dev
spec:
  selector:
    app: smtp4dev
  ports:
    - name: web
      port: 5000
      targetPort: 80
    - name: smtp
      port: 25
      targetPort: 25
    - name: imap
      port: 143
      targetPort: 143
  type: ClusterIP
