eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

grpc:
  client:
    user:
      address: 'static://127.0.0.1:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    aggregator:
      address: 'static://127.0.0.1:50054'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  port: 8092

spring:
  application:
    name: notification-service
  mail:
    host: localhost
    port: 25
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  internal:
    user:
      base-url: http://localhost:8081
    aggregator:
      base-url: http://localhost:8084
