management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    mail:
      # Turn off health check mail server
      enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411
      connect-timeout: 30s
      read-timeout: 10s
  tracing:
    sampling:
      # 1.0 represents 100%, meaning all requests will be traced.
      probability: 1.0

server:
  port: 8092

spring:
  application:
    name: notification-server
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: localhost
    port: 25

app:
  event:
    kafka:
      consumer:
        topics: order_confirmed,order_canceled
