version: "3"

services:

  activemq:
    container_name: activemq
    image: apache/activemq-artemis:latest-alpine
    ports:
      - "8161:8161" # Admin console (artemis/artemis)
      - "61616:61616" # JMX
    volumes:
      - activemq-data:/data/activemq
      - activemq-log:/var/log/activemq

volumes:
  activemq-data:
  activemq-log:
