version: "3"

services:

  cassandra1:
    container_name: cassandra1
    image: cassandra:3.11
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra1:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: docker
      # By default, Cassandra autodetect the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M

  cassandra2:
    container_name: cassandra2
    image: cassandra:3.11
    ports:
      - "9043:9042"
      - "7001:7000"
    volumes:
      - cassandra2:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: docker
      CASSANDRA_SEEDS: cassandra1
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M
    depends_on:
      - cassandra1

volumes:
  cassandra1:
  cassandra2:
