version: "3"

services:
  consul:
    container_name: consul
    image: consul:1.6
    ports:
      - "8500:8500"
    volumes:
      - consul-data:/consul/data
      - consul-config:/consul/config

volumes:
  consul-data:
  consul-config:
