# Before running build.sh script, please use this sql `SELECT @@server_id;` to verify server_id of master and slave.
# Their server_id should be different.

version: "3"

services:

  mysql_master:
    container_name: mysql_master
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./mysql-8-master-slave/conf/master.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-8-master-slave/script:/docker-entrypoint-initdb.d
      - mysql-master-data:/var/lib/mysql
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*.cnf
      && /entrypoint.sh mysqld
      "

  mysql_slave:
    container_name: mysql_slave
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./mysql-8-master-slave/conf/slave.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-slave-data:/var/lib/mysql
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*.cnf
      && /entrypoint.sh mysqld
      "
    depends_on:
      - mysql_master

volumes:
  mysql-master-data:
  mysql-slave-data:
