version: "3"

services:

  loki:
    container_name: loki
    image: grafana/loki:main
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail:main
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./observability-v1/promtail-config.yml:/etc/promtail/config.yml
      - D:/logs:/opt/app/logs # Mount local log to loki filesystem

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability-v1/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: mem

volumes:
  grafana-data:
