version: '3'

services:

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.82.0
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    command: --config=/etc/otelcol-cont/otel-collector.yml
    volumes:
      - ./observability-v2/otel-collector.yml:/etc/otelcol-cont/otel-collector.yml

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./observability-v2/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4317"      # OTLP gRPC receiver
    command: -config.file=/etc/tempo.yml
    volumes:
      - ./observability-v2/tempo.yml:/etc/tempo.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
