version: "3"

services:

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    command: redis-server --requirepass 123456

volumes:
  redis-data:
