# Refer https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml

version: "3"

services:

  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev
    ports:
      - "5000:80" # Web interface
      - "25:25"   # SMTP server
      - "143:143" # IMAP server
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  smtp4dev-data:
