version: "3"

services:

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.14
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

volumes:
  zookeeper-data:
  zookeeper-log:
