spring:
  quartz:
    # Quartz can store job and scheduling information in a relational database or RAM.
    # With RAM option, any information will be deleted with application restart.
    job-store-type: memory
    properties:
      org.quartz.scheduler:
        instanceName: DefaultScheduler
        instanceId: AUTO
      org.quartz.threadPool:
        threadNamePrefix: quartz
        threadCount: 10
