server:
  http_listen_port: 9080 # Optional: This port is used to access Promtail status and metrics endpoints
  grpc_listen_port: 0    # Optional: Disable gRPC server (set to 0 to disable)

positions:
  filename: /var/log/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# __path__ points to the path of destination directory inside promtail container
scrape_configs:
  - job_name: eureka-server
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: eureka-server
          __path__: /var/log/eureka-server/*.log
  - job_name: user-service
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: user-service
          __path__: /var/log/user-service/*.log
  - job_name: product-service
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: product-service
          __path__: /var/log/product-service/*.log
  - job_name: order-service
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: order-service
          __path__: /var/log/order-service/*.log
  - job_name: gateway-server
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: gateway-server
          __path__: /var/log/gateway-server/*.log
  - job_name: auth-service
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: auth-service
          __path__: /var/log/auth-service/*.log
  - job_name: notification-service
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: notification-service
          __path__: /var/log/notification-service/*.log
  - job_name: job-service
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: job-service
          __path__: /var/log/job-service/*.log
