DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS outbox_message;

CREATE TABLE users
(
    id         INT            NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username   VARCHAR(255)   NOT NULL,
    email      VARCHAR(255)   NOT NULL,
    password   VARCHAR(255)   NOT NULL,
    role       VARCHAR(255)   NOT NULL,
    credit     DECIMAL(11, 2) NOT NULL DEFAULT 0,
    created_at DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME                DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE outbox_message
(
    id         BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    event      VARCHAR(1000) NOT NULL,
    created_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME               DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB;
