server:
  port: 8080

spring:
  application:
    name: gateway-server
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

springdoc:
  swagger-ui:
    urls:
      - name: auth-server
        url: /auth-server/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: aggregator-service
        url: /aggregator-service/v3/api-docs
