eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

grpc:
  client:
    user:
      address: ${GRPC_CLIENT_USER_ADDRESS:'static://127.0.0.1:50051'}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    mail:
      # Turn off health check mail server
      enabled: false
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411}
      connect-timeout: 30s
      read-timeout: 10s
  tracing:
    sampling:
      # 1.0 represents 100%, meaning all requests will be traced.
      probability: 1.0

server:
  port: 8091

spring:
  application:
    name: auth-server
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:123456}

springdoc:
  packages-to-scan: org.atlas.auth.api.controller

app:
  rest:
    user:
      base-url: ${REST_USER_BASE_URL:http://localhost:8081}
