eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

grpc:
  client:
    user:
      address: 'static://127.0.0.1:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  port: 8091

spring:
  application:
    name: auth-server
  data:
    redis:
      host: localhost
      password: 123456
      port: 6379

springdoc:
  packages-to-scan: org.atlas.auth.api.controller

app:
  internal:
    user:
      base-url: http://localhost:8081
