# Disable the Eureka discovery client, and use Kubernetes built-in DNS for service discovery.
eureka:
  client:
    enabled: false

spring:
  cloud:
    kubernetes:
      loadbalancer:
        mode: SERVICE
