// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aggregator.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.aggregator;

public interface OrderItemProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aggregator.OrderItemProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 product_id = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>string product_name = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>double product_price = 3;</code>
   * @return The productPrice.
   */
  double getProductPrice();

  /**
   * <code>string product_status = 4;</code>
   * @return The productStatus.
   */
  java.lang.String getProductStatus();
  /**
   * <code>string product_status = 4;</code>
   * @return The bytes for productStatus.
   */
  com.google.protobuf.ByteString
      getProductStatusBytes();

  /**
   * <code>int32 quantity = 5;</code>
   * @return The quantity.
   */
  int getQuantity();
}
