// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aggregator.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.aggregator;

/**
 * Protobuf type {@code aggregator.OrderProto}
 */
public final class OrderProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aggregator.OrderProto)
    OrderProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderProto.newBuilder() to construct.
  private OrderProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderProto() {
    status_ = "";
    orderItem_ = java.util.Collections.emptyList();
    createdAt_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.atlas.framework.grpc.protobuf.aggregator.Aggregator.internal_static_aggregator_OrderProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.atlas.framework.grpc.protobuf.aggregator.Aggregator.internal_static_aggregator_OrderProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.atlas.framework.grpc.protobuf.aggregator.OrderProto.class, org.atlas.framework.grpc.protobuf.aggregator.OrderProto.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int CUSTOMER_FIELD_NUMBER = 2;
  private org.atlas.framework.grpc.protobuf.aggregator.CustomerProto customer_;
  /**
   * <code>.aggregator.CustomerProto customer = 2;</code>
   * @return Whether the customer field is set.
   */
  @java.lang.Override
  public boolean hasCustomer() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.aggregator.CustomerProto customer = 2;</code>
   * @return The customer.
   */
  @java.lang.Override
  public org.atlas.framework.grpc.protobuf.aggregator.CustomerProto getCustomer() {
    return customer_ == null ? org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.getDefaultInstance() : customer_;
  }
  /**
   * <code>.aggregator.CustomerProto customer = 2;</code>
   */
  @java.lang.Override
  public org.atlas.framework.grpc.protobuf.aggregator.CustomerProtoOrBuilder getCustomerOrBuilder() {
    return customer_ == null ? org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.getDefaultInstance() : customer_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private double amount_ = 0D;
  /**
   * <code>double amount = 3;</code>
   * @return The amount.
   */
  @java.lang.Override
  public double getAmount() {
    return amount_;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_ITEM_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto> orderItem_;
  /**
   * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
   */
  @java.lang.Override
  public java.util.List<org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto> getOrderItemList() {
    return orderItem_;
  }
  /**
   * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.atlas.framework.grpc.protobuf.aggregator.OrderItemProtoOrBuilder> 
      getOrderItemOrBuilderList() {
    return orderItem_;
  }
  /**
   * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
   */
  @java.lang.Override
  public int getOrderItemCount() {
    return orderItem_.size();
  }
  /**
   * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
   */
  @java.lang.Override
  public org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto getOrderItem(int index) {
    return orderItem_.get(index);
  }
  /**
   * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
   */
  @java.lang.Override
  public org.atlas.framework.grpc.protobuf.aggregator.OrderItemProtoOrBuilder getOrderItemOrBuilder(
      int index) {
    return orderItem_.get(index);
  }

  public static final int CREATED_AT_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object createdAt_ = "";
  /**
   * <code>string created_at = 6;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public java.lang.String getCreatedAt() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdAt_ = s;
      return s;
    }
  }
  /**
   * <code>string created_at = 6;</code>
   * @return The bytes for createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedAtBytes() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getCustomer());
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      output.writeDouble(3, amount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
    }
    for (int i = 0; i < orderItem_.size(); i++) {
      output.writeMessage(5, orderItem_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createdAt_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, createdAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCustomer());
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, amount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
    }
    for (int i = 0; i < orderItem_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, orderItem_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createdAt_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, createdAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.atlas.framework.grpc.protobuf.aggregator.OrderProto)) {
      return super.equals(obj);
    }
    org.atlas.framework.grpc.protobuf.aggregator.OrderProto other = (org.atlas.framework.grpc.protobuf.aggregator.OrderProto) obj;

    if (getId()
        != other.getId()) return false;
    if (hasCustomer() != other.hasCustomer()) return false;
    if (hasCustomer()) {
      if (!getCustomer()
          .equals(other.getCustomer())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getAmount())
        != java.lang.Double.doubleToLongBits(
            other.getAmount())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getOrderItemList()
        .equals(other.getOrderItemList())) return false;
    if (!getCreatedAt()
        .equals(other.getCreatedAt())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (hasCustomer()) {
      hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
      hash = (53 * hash) + getCustomer().hashCode();
    }
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    if (getOrderItemCount() > 0) {
      hash = (37 * hash) + ORDER_ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getOrderItemList().hashCode();
    }
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedAt().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.atlas.framework.grpc.protobuf.aggregator.OrderProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aggregator.OrderProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aggregator.OrderProto)
      org.atlas.framework.grpc.protobuf.aggregator.OrderProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.atlas.framework.grpc.protobuf.aggregator.Aggregator.internal_static_aggregator_OrderProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.atlas.framework.grpc.protobuf.aggregator.Aggregator.internal_static_aggregator_OrderProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.atlas.framework.grpc.protobuf.aggregator.OrderProto.class, org.atlas.framework.grpc.protobuf.aggregator.OrderProto.Builder.class);
    }

    // Construct using org.atlas.framework.grpc.protobuf.aggregator.OrderProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCustomerFieldBuilder();
        getOrderItemFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      customer_ = null;
      if (customerBuilder_ != null) {
        customerBuilder_.dispose();
        customerBuilder_ = null;
      }
      amount_ = 0D;
      status_ = "";
      if (orderItemBuilder_ == null) {
        orderItem_ = java.util.Collections.emptyList();
      } else {
        orderItem_ = null;
        orderItemBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      createdAt_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.atlas.framework.grpc.protobuf.aggregator.Aggregator.internal_static_aggregator_OrderProto_descriptor;
    }

    @java.lang.Override
    public org.atlas.framework.grpc.protobuf.aggregator.OrderProto getDefaultInstanceForType() {
      return org.atlas.framework.grpc.protobuf.aggregator.OrderProto.getDefaultInstance();
    }

    @java.lang.Override
    public org.atlas.framework.grpc.protobuf.aggregator.OrderProto build() {
      org.atlas.framework.grpc.protobuf.aggregator.OrderProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.atlas.framework.grpc.protobuf.aggregator.OrderProto buildPartial() {
      org.atlas.framework.grpc.protobuf.aggregator.OrderProto result = new org.atlas.framework.grpc.protobuf.aggregator.OrderProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.atlas.framework.grpc.protobuf.aggregator.OrderProto result) {
      if (orderItemBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          orderItem_ = java.util.Collections.unmodifiableList(orderItem_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.orderItem_ = orderItem_;
      } else {
        result.orderItem_ = orderItemBuilder_.build();
      }
    }

    private void buildPartial0(org.atlas.framework.grpc.protobuf.aggregator.OrderProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.customer_ = customerBuilder_ == null
            ? customer_
            : customerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.createdAt_ = createdAt_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.atlas.framework.grpc.protobuf.aggregator.OrderProto) {
        return mergeFrom((org.atlas.framework.grpc.protobuf.aggregator.OrderProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.atlas.framework.grpc.protobuf.aggregator.OrderProto other) {
      if (other == org.atlas.framework.grpc.protobuf.aggregator.OrderProto.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.hasCustomer()) {
        mergeCustomer(other.getCustomer());
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (orderItemBuilder_ == null) {
        if (!other.orderItem_.isEmpty()) {
          if (orderItem_.isEmpty()) {
            orderItem_ = other.orderItem_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureOrderItemIsMutable();
            orderItem_.addAll(other.orderItem_);
          }
          onChanged();
        }
      } else {
        if (!other.orderItem_.isEmpty()) {
          if (orderItemBuilder_.isEmpty()) {
            orderItemBuilder_.dispose();
            orderItemBuilder_ = null;
            orderItem_ = other.orderItem_;
            bitField0_ = (bitField0_ & ~0x00000010);
            orderItemBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderItemFieldBuilder() : null;
          } else {
            orderItemBuilder_.addAllMessages(other.orderItem_);
          }
        }
      }
      if (!other.getCreatedAt().isEmpty()) {
        createdAt_ = other.createdAt_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getCustomerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              amount_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto m =
                  input.readMessage(
                      org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.parser(),
                      extensionRegistry);
              if (orderItemBuilder_ == null) {
                ensureOrderItemIsMutable();
                orderItem_.add(m);
              } else {
                orderItemBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              createdAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private org.atlas.framework.grpc.protobuf.aggregator.CustomerProto customer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.atlas.framework.grpc.protobuf.aggregator.CustomerProto, org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.Builder, org.atlas.framework.grpc.protobuf.aggregator.CustomerProtoOrBuilder> customerBuilder_;
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     * @return Whether the customer field is set.
     */
    public boolean hasCustomer() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     * @return The customer.
     */
    public org.atlas.framework.grpc.protobuf.aggregator.CustomerProto getCustomer() {
      if (customerBuilder_ == null) {
        return customer_ == null ? org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.getDefaultInstance() : customer_;
      } else {
        return customerBuilder_.getMessage();
      }
    }
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     */
    public Builder setCustomer(org.atlas.framework.grpc.protobuf.aggregator.CustomerProto value) {
      if (customerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        customer_ = value;
      } else {
        customerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     */
    public Builder setCustomer(
        org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.Builder builderForValue) {
      if (customerBuilder_ == null) {
        customer_ = builderForValue.build();
      } else {
        customerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     */
    public Builder mergeCustomer(org.atlas.framework.grpc.protobuf.aggregator.CustomerProto value) {
      if (customerBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          customer_ != null &&
          customer_ != org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.getDefaultInstance()) {
          getCustomerBuilder().mergeFrom(value);
        } else {
          customer_ = value;
        }
      } else {
        customerBuilder_.mergeFrom(value);
      }
      if (customer_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     */
    public Builder clearCustomer() {
      bitField0_ = (bitField0_ & ~0x00000002);
      customer_ = null;
      if (customerBuilder_ != null) {
        customerBuilder_.dispose();
        customerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     */
    public org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.Builder getCustomerBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCustomerFieldBuilder().getBuilder();
    }
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     */
    public org.atlas.framework.grpc.protobuf.aggregator.CustomerProtoOrBuilder getCustomerOrBuilder() {
      if (customerBuilder_ != null) {
        return customerBuilder_.getMessageOrBuilder();
      } else {
        return customer_ == null ?
            org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.getDefaultInstance() : customer_;
      }
    }
    /**
     * <code>.aggregator.CustomerProto customer = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.atlas.framework.grpc.protobuf.aggregator.CustomerProto, org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.Builder, org.atlas.framework.grpc.protobuf.aggregator.CustomerProtoOrBuilder> 
        getCustomerFieldBuilder() {
      if (customerBuilder_ == null) {
        customerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.atlas.framework.grpc.protobuf.aggregator.CustomerProto, org.atlas.framework.grpc.protobuf.aggregator.CustomerProto.Builder, org.atlas.framework.grpc.protobuf.aggregator.CustomerProtoOrBuilder>(
                getCustomer(),
                getParentForChildren(),
                isClean());
        customer_ = null;
      }
      return customerBuilder_;
    }

    private double amount_ ;
    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 3;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(double value) {

      amount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      amount_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 4;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 4;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 4;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.util.List<org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto> orderItem_ =
      java.util.Collections.emptyList();
    private void ensureOrderItemIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        orderItem_ = new java.util.ArrayList<org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto>(orderItem_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProtoOrBuilder> orderItemBuilder_;

    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public java.util.List<org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto> getOrderItemList() {
      if (orderItemBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderItem_);
      } else {
        return orderItemBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public int getOrderItemCount() {
      if (orderItemBuilder_ == null) {
        return orderItem_.size();
      } else {
        return orderItemBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto getOrderItem(int index) {
      if (orderItemBuilder_ == null) {
        return orderItem_.get(index);
      } else {
        return orderItemBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder setOrderItem(
        int index, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto value) {
      if (orderItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderItemIsMutable();
        orderItem_.set(index, value);
        onChanged();
      } else {
        orderItemBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder setOrderItem(
        int index, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder builderForValue) {
      if (orderItemBuilder_ == null) {
        ensureOrderItemIsMutable();
        orderItem_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderItemBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder addOrderItem(org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto value) {
      if (orderItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderItemIsMutable();
        orderItem_.add(value);
        onChanged();
      } else {
        orderItemBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder addOrderItem(
        int index, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto value) {
      if (orderItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderItemIsMutable();
        orderItem_.add(index, value);
        onChanged();
      } else {
        orderItemBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder addOrderItem(
        org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder builderForValue) {
      if (orderItemBuilder_ == null) {
        ensureOrderItemIsMutable();
        orderItem_.add(builderForValue.build());
        onChanged();
      } else {
        orderItemBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder addOrderItem(
        int index, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder builderForValue) {
      if (orderItemBuilder_ == null) {
        ensureOrderItemIsMutable();
        orderItem_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderItemBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder addAllOrderItem(
        java.lang.Iterable<? extends org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto> values) {
      if (orderItemBuilder_ == null) {
        ensureOrderItemIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderItem_);
        onChanged();
      } else {
        orderItemBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder clearOrderItem() {
      if (orderItemBuilder_ == null) {
        orderItem_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        orderItemBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public Builder removeOrderItem(int index) {
      if (orderItemBuilder_ == null) {
        ensureOrderItemIsMutable();
        orderItem_.remove(index);
        onChanged();
      } else {
        orderItemBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder getOrderItemBuilder(
        int index) {
      return getOrderItemFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public org.atlas.framework.grpc.protobuf.aggregator.OrderItemProtoOrBuilder getOrderItemOrBuilder(
        int index) {
      if (orderItemBuilder_ == null) {
        return orderItem_.get(index);  } else {
        return orderItemBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public java.util.List<? extends org.atlas.framework.grpc.protobuf.aggregator.OrderItemProtoOrBuilder> 
         getOrderItemOrBuilderList() {
      if (orderItemBuilder_ != null) {
        return orderItemBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderItem_);
      }
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder addOrderItemBuilder() {
      return getOrderItemFieldBuilder().addBuilder(
          org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.getDefaultInstance());
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder addOrderItemBuilder(
        int index) {
      return getOrderItemFieldBuilder().addBuilder(
          index, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.getDefaultInstance());
    }
    /**
     * <code>repeated .aggregator.OrderItemProto order_item = 5;</code>
     */
    public java.util.List<org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder> 
         getOrderItemBuilderList() {
      return getOrderItemFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProtoOrBuilder> 
        getOrderItemFieldBuilder() {
      if (orderItemBuilder_ == null) {
        orderItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProto.Builder, org.atlas.framework.grpc.protobuf.aggregator.OrderItemProtoOrBuilder>(
                orderItem_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        orderItem_ = null;
      }
      return orderItemBuilder_;
    }

    private java.lang.Object createdAt_ = "";
    /**
     * <code>string created_at = 6;</code>
     * @return The createdAt.
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created_at = 6;</code>
     * @return The bytes for createdAt.
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_at = 6;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      createdAt_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string created_at = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      createdAt_ = getDefaultInstance().getCreatedAt();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string created_at = 6;</code>
     * @param value The bytes for createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      createdAt_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aggregator.OrderProto)
  }

  // @@protoc_insertion_point(class_scope:aggregator.OrderProto)
  private static final org.atlas.framework.grpc.protobuf.aggregator.OrderProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.atlas.framework.grpc.protobuf.aggregator.OrderProto();
  }

  public static org.atlas.framework.grpc.protobuf.aggregator.OrderProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderProto>
      PARSER = new com.google.protobuf.AbstractParser<OrderProto>() {
    @java.lang.Override
    public OrderProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OrderProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.atlas.framework.grpc.protobuf.aggregator.OrderProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

