server:
  http_listen_port: 9080 # Optional: This port is used to access Promtail status and metrics endpoints
  grpc_listen_port: 0    # Optional: Disable gRPC server (set to 0 to disable)

positions:
  filename: /var/log/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: user-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          __path__: /opt/app/logs/user-service/*.log
