// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.product;

public interface CategoryListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.CategoryListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .product.CategoryProto category = 1;</code>
   */
  java.util.List<org.atlas.framework.grpc.protobuf.product.CategoryProto> 
      getCategoryList();
  /**
   * <code>repeated .product.CategoryProto category = 1;</code>
   */
  org.atlas.framework.grpc.protobuf.product.CategoryProto getCategory(int index);
  /**
   * <code>repeated .product.CategoryProto category = 1;</code>
   */
  int getCategoryCount();
  /**
   * <code>repeated .product.CategoryProto category = 1;</code>
   */
  java.util.List<? extends org.atlas.framework.grpc.protobuf.product.CategoryProtoOrBuilder> 
      getCategoryOrBuilderList();
  /**
   * <code>repeated .product.CategoryProto category = 1;</code>
   */
  org.atlas.framework.grpc.protobuf.product.CategoryProtoOrBuilder getCategoryOrBuilder(
      int index);
}
