// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.product;

public final class Product {
  private Product() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ListProductRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ListProductRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductListProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductListProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\007product\032\033google/protobu" +
      "f/empty.proto\"%\n\027ListProductRequestProto" +
      "\022\n\n\002id\030\001 \003(\005\"7\n\014ProductProto\022\n\n\002id\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\022\r\n\005price\030\003 \001(\001\":\n\020Product" +
      "ListProto\022&\n\007product\030\001 \003(\0132\025.product.Pro" +
      "ductProto2^\n\016ProductService\022L\n\013ListProdu" +
      "ct\022 .product.ListProductRequestProto\032\031.p" +
      "roduct.ProductListProto\"\000B-\n)org.atlas.f" +
      "ramework.grpc.protobuf.productP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_product_ListProductRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_product_ListProductRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ListProductRequestProto_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_product_ProductProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_product_ProductProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductProto_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", });
    internal_static_product_ProductListProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_product_ProductListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductListProto_descriptor,
        new java.lang.String[] { "Product", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
