// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.customer;

public interface CustomerListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.CustomerListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .common.CustomerProto customer = 1;</code>
   */
  java.util.List<org.atlas.framework.grpc.protobuf.common.CustomerProto> 
      getCustomerList();
  /**
   * <code>repeated .common.CustomerProto customer = 1;</code>
   */
  org.atlas.framework.grpc.protobuf.common.CustomerProto getCustomer(int index);
  /**
   * <code>repeated .common.CustomerProto customer = 1;</code>
   */
  int getCustomerCount();
  /**
   * <code>repeated .common.CustomerProto customer = 1;</code>
   */
  java.util.List<? extends org.atlas.framework.grpc.protobuf.common.CustomerProtoOrBuilder> 
      getCustomerOrBuilderList();
  /**
   * <code>repeated .common.CustomerProto customer = 1;</code>
   */
  org.atlas.framework.grpc.protobuf.common.CustomerProtoOrBuilder getCustomerOrBuilder(
      int index);
}
