// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

// Protobuf Java Version: 3.25.1
package org.atlas.framework.grpc.protobuf.customer;

public interface ListCustomerRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.ListCustomerRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 user_id = 1;</code>
   * @return A list containing the userId.
   */
  java.util.List<java.lang.Integer> getUserIdList();
  /**
   * <code>repeated int32 user_id = 1;</code>
   * @return The count of userId.
   */
  int getUserIdCount();
  /**
   * <code>repeated int32 user_id = 1;</code>
   * @param index The index of the element to return.
   * @return The userId at the given index.
   */
  int getUserId(int index);
}
